# Generated by Django 4.0.4 on 2022-05-29 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['city']},
        ),
        migrations.RemoveField(
            model_name='location',
            name='country',
        ),
    ]
